export const KZ_CITIES = [
  { label: "Алматы",        value: "Алматы",        type: "regional" },
  { label: "Астана",        value: "Астана",         type: "regional" },
  { label: "Шымкент",       value: "Шымкент",        type: "regional" },
  { label: "Актобе",        value: "Актобе",         type: "regional" },
  { label: "Атырау",        value: "Атырау",         type: "regional" },
  { label: "Актау",         value: "Актау",          type: "regional" },
  { label: "Кокшетау",      value: "Кокшетау",       type: "regional" },
  { label: "Костанай",      value: "Костанай",       type: "regional" },
  { label: "Кызылорда",     value: "Кызылорда",      type: "regional" },
  { label: "Оскемен",       value: "Оскемен",        type: "regional" },
  { label: "Павлодар",      value: "Павлодар",       type: "regional" },
  { label: "Петропавловск", value: "Петропавловск",  type: "regional" },
  { label: "Семей",         value: "Семей",          type: "regional" },
  { label: "Талдыкорган",   value: "Талдыкорган",    type: "regional" },
  { label: "Тараз",         value: "Тараз",          type: "regional" },
  { label: "Уральск",       value: "Уральск",        type: "regional" },
  { label: "Жезказган",     value: "Жезказган",      type: "regional" },
  { label: "Караганда",     value: "Караганда",      type: "regional" },
  { label: "Темиртау",      value: "Темиртау",       type: "district" },
  { label: "Экибастуз",     value: "Экибастуз",      type: "district" },
  { label: "Рудный",        value: "Рудный",         type: "district" },
  { label: "Степногорск",   value: "Степногорск",    type: "district" },
  { label: "Капшагай",      value: "Капшагай",       type: "district" },
  { label: "Туркестан",     value: "Туркестан",      type: "district" },
  { label: "Балхаш",        value: "Балхаш",         type: "district" },
  { label: "Талгар",        value: "Талгар",         type: "district" },
  { label: "Каскелен",      value: "Каскелен",       type: "district" },
  { label: "Аксай",         value: "Аксай",          type: "district" },
  { label: "Жанаозен",      value: "Жанаозен",       type: "district" },
  { label: "Риддер",        value: "Риддер",         type: "district" },
  { label: "Жаркент",       value: "Жаркент",        type: "district" },
] as const;

export type CityOption = { label: string; value: string; type: "regional" | "district" };
